### PR TITLE
Landing page updated

### PR DESCRIPTION
**Pull request by Socram1**
Added basic styling to the landing page.

### CODE REVIEW

**Comment by jeanlange** [comment]
Great progress!

image

some things I see in looking at this locally that I'd like to have you address before merging:
- 'Find a race' overlaps 'Search Races'
- headers on table don't match up with table columns
- picture stretches oddly with the page, making the people weirdly thin/thick
- picture is predominantly (completely?) men.

**Comment by Socram1** [comment]
On it! Not sure why the search bar overlaps on yours but not on mine though. I wanted to discuss that in teams, because locally for me it looks good
Screenshot (338)
. Maybe I can delete "Find Race" completely and just leave the search bar??

**Comment by jeanlange** [comment]
It's possible that we're using different browsers? I'm on Chrome.

**Review by GamingViking — APPROVED** [review]
Nice updates!

**Pull request merged**
